# Generated by Django 4.2.17 on 2024-12-20 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_rename_orders_payment_order_payment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='order',
            new_name='orders',
        ),
    ]
